
#services:
###> doctrine/doctrine-bundle ###
#  database:
#    ports:
#      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
#  mailer:
#    image: axllent/mailpit
#    ports:
#      - "1025"
#      - "8025"
#    environment:
#      MP_SMTP_AUTH_ACCEPT_ANY: 1
#      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

version: '3.8'

services:
  apache_php:
    image: php:8.3.16-apache
    container_name: symfony_app
    ports:
      - "8000:80"
    volumes:
      - C:\laragon\www\
    depends_on:
      - db
    networks:
      - symfony_net

  db:
    image: mysql:8.4.3
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - symfony_net

volumes:
  db_data:

networks:
  symfony_net:
    driver: bridge 

